cmake_minimum_required(VERSION 3.16)
project(oculus_driver VERSION 2.0.0)

option(BUILD_TESTS "Build unit tests" OFF)
option(BUILD_PYTHON "Build python bindings" OFF)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/DefaultBuildType.cmake)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(PkgConfig REQUIRED)
find_package(Boost COMPONENTS system thread REQUIRED)
pkg_check_modules(FMT fmt)
message(STATUS "FMT_VERSION: ${FMT_VERSION}")
message(STATUS "FMT_LIBRARY_DIRS = ${FMT_LIBRARY_DIRS}")
message(STATUS "FMT_LIBRARIES = ${FMT_LIBRARIES}")

find_package(spdlog REQUIRED)
set(SPDLOG_LIB spdlog::spdlog)

if("${SPDLOG_LIBRARIES}" STREQUAL "")
    set(SPDLOG_LIBRARIES spdlog::spdlog)
endif()

find_package(eventpp CONFIG REQUIRED)
find_package(magic_enum CONFIG REQUIRED)

if("${magic_enum_LIBRARIES}" STREQUAL "")
    set(magic_enum_LIBRARIES magic_enum::magic_enum)
endif()

add_definitions(-DSPDLOG_COMPILED_LIB)
add_definitions(-DSPDLOG_FMT_EXTERNAL=1)

message(STATUS "BUILD_TESTS: ${BUILD_TESTS}")

set(EXT_LIBS
    Boost::system
    Boost::thread
    ${magic_enum_LIBRARIES}
    ${SPDLOG_LIBRARIES}
    ${FMT_LIBRARIES}
)

set(EXT_LIB_DIRS
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
    ${EVENTPP_INCLUDE_DIR}
    ${magic_enum_INCLUDE_DIRS}
    ${FMT_LIBRARY_DIRS}
)
message(STATUS "EXT_LIB_DIRS: ${EXT_LIB_DIRS}")
message(STATUS "EXT_LIBS: ${EXT_LIBS}")

add_library(oculus_driver SHARED
    src/AsyncService.cpp
    src/print_utils.cpp
    src/Recorder.cpp
    src/SonarClient.cpp
    src/SonarDriver.cpp
    src/StatusListener.cpp
)

target_include_directories(oculus_driver PUBLIC ${EXT_LIB_DIRS})
target_link_directories(oculus_driver PUBLIC ${EXT_LIB_DIRS})
target_link_libraries(oculus_driver PUBLIC ${EXT_LIBS})
target_compile_definitions(oculus_driver PUBLIC MAGIC_ENUM_RANGE_MAX=1024)

# ############
# # Install ##
# ############
include(GNUInstallDirs)

install(DIRECTORY include/oculus_driver
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

install(TARGETS ${PROJECT_NAME}
    DESTINATION ${CMAKE_INSTALL_LIBDIR})

# ###########
# # Config ##
# ###########
set(INCLUDE_INSTALL_DIR include)
set(LIB_INSTALL_DIR lib)

include(CMakePackageConfigHelpers)
configure_package_config_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Config.cmake.in
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
    PATH_VARS INCLUDE_INSTALL_DIR LIB_INSTALL_DIR
)
write_basic_package_version_file(
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
    VERSION "${CMAKE_PROJECT_VERSION}"
    COMPATIBILITY AnyNewerVersion
)
install(FILES
    ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake
    ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake
    DESTINATION lib/cmake/${PROJECT_NAME}
)

if(BUILD_PYTHON)
    add_subdirectory(python)

    # Run the pip3 command to install the package
    execute_process(
        COMMAND pip3 install --user -e ${CMAKE_SOURCE_DIR}/python
        RESULT_VARIABLE PIP_INSTALL_RESULT
    )
    # Check if the installation was successful
    if(NOT PIP_INSTALL_RESULT EQUAL "0")
        message(FATAL_ERROR "Failed to install oculus_driver_python package with pip3")
    endif()
endif()

if(BUILD_TESTS)
    add_subdirectory(tests)
endif()
